version: '3.8'
services:
  crm:
    build: ./micro-crm
  mailing:
    build: ./micro-mailing
    ports:
    - "8080:8080"
    depends_on: 
      - hc1
      - hc2
      - hc3
  hc1:
    image: hazelcast/hazelcast
  hc2:
    image: hazelcast/hazelcast
  hc3:
    image: hazelcast/hazelcast
  management-center:
    image: hazelcast/management-center
    ports:
      - '8090:8080'
