global:
  scrape_interval: 10s
  evaluation_interval: 30s
  external_labels:
    monitor: 'codelab-monitor'

scrape_configs:
 # - job_name: 'failing'
 #   metrics_path: '/actuator/prometheus'
 #   scrape_interval: 5s
 #   static_configs:
 #     - targets: ['failingljsdlfkjskldfjs.com']

  - job_name: 'monitoring-app'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['monitoring-app:8080']
    # basic_auth:
    #   username: todo_user
    #   password: todo_pass
    # scheme: https
