apiVersion: apps/v1
kind: Deployment
metadata:
  name: products-deployment
  labels:
    app: products
spec:
  replicas: 2
  selector:
    matchLabels:
      app: products
  template:
    metadata:
      labels:
        app: products
    spec:
      containers:
        - name: products
          image: jirkapinkas/micro-products:latest
          ports:
            - containerPort: 8080
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 600
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 600
          # resources:
          #   limits:
          #     memory: "512Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: products
  labels:
    app: products
spec:
  selector:
    app: products
  ports:
    - name: http
      port: 8080
      targetPort: 8080
