version: '3'
services:
  elasticsearch:
    image: "elasticsearch:7.8.0"
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      discovery.type: single-node
  kibana:
    image: "kibana:7.8.0"
    ports:
      - "5601:5601"
    environment:
      ELASTICSEARCH_HOSTS: http://elasticsearch:9200
  filebeat:
    image: "docker.elastic.co/beats/filebeat:7.8.0"
    user: root
    volumes:
      - ./filebeat.yml:/usr/share/filebeat/filebeat.yml
      - /var/lib/docker/:/var/lib/docker
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - elasticsearch

